with open("validation_maps.py", "r") as f:
    content = f.read()

# Insert the static HUC-12 lookup table after the imports
LOOKUP = '''
# ==============================================================================
# STATIC HUC-12 LOOKUP — WatershedID → huc12 code
# Generated by point-in-polygon join against USGS/WBD/2017/HUC12
# Each WatershedID maps to the HUC-12 polygon containing its deposit point.
# ==============================================================================
_WATERSHED_TO_HUC12 = {
    # GRAND PRIX
    "GrandPrix1": "180702030305",
    "GrandPrix2": "180702030804",
    "GrandPrix3": "180702030704",
    "GrandPrix4": "180702030704",
    "GrandPrix5": "180702030303",
    "GrandPrix6": "180702030303",
    "GrandPrix7": "180702030305",
    # STATION
    "Station1":  "180701050105",
    "Station2":  "180701050207",
    "Station3":  "180701050207",
    "Station4":  "180701050207",
    "Station5":  "180701050207",
    "Station6":  "180701050207",
    "Station7":  "180701050207",
    "Station8":  "180701050207",
    "Station9":  "180701050207",
    "Station10": "180701050207",
    "Station11": "180701050207",
    "Station12": "180701050207",
    "Station13": "180701050207",
    "Station14": "180701050207",
    "Station15": "180701050207",
    "Station16": "180701050209",
    "Station17": "180701050209",
    "Station18": "180701050209",
    "Station19": "180701050209",
    "Station20": "180701050209",
    # THOMAS
    "Thomas1": "180600130203",
    "Thomas2": "180600130203",
    "Thomas3": "180600130203",
    "Thomas4": "180600130203",
    "Thomas5": "180600130203",
}

'''

# Insert after the last import line
import_end = content.rfind("\nimport ")
next_newline = content.find("\n", import_end + 1)
content = content[:next_newline+1] + LOOKUP + content[next_newline+1:]

# Replace the ratio_lookup builder to use the static HUC-12 map
old = '''    # ── Build ratio lookup keyed by huc12 ID ─────────────────────────────────
    # We match HUC-12 polygons to basin residuals via WatershedID.
    # WatershedID in the CSV is expected to be a 12-digit HUC code or a name.
    # We build a ratio lookup on WatershedID stripped to digits for fuzzy match.
    ratio_lookup: dict[str, float] = {}
    for _, row in df.iterrows():
        wid = str(row["WatershedID"]).strip()
        ratio_lookup[wid] = float(row["Ratio"])
        # Also index by trailing 12 digits in case of padded codes
        digits = "".join(filter(str.isdigit, wid))
        if digits:
            ratio_lookup[digits] = float(row["Ratio"])'''

new = '''    # ── Build ratio lookup keyed by huc12 ID ─────────────────────────────────
    # WatershedIDs in the CSV (e.g. "GrandPrix1") are matched to 12-digit
    # HUC codes via the static lookup table built by point-in-polygon join.
    # Multiple WatershedIDs can share a HUC-12 — we average their ratios.
    from collections import defaultdict
    huc12_ratio_sum: dict[str, list] = defaultdict(list)
    for _, row in df.iterrows():
        wid = str(row["WatershedID"]).strip()
        huc_code = _WATERSHED_TO_HUC12.get(wid)
        if huc_code:
            huc12_ratio_sum[huc_code].append(float(row["Ratio"]))
    ratio_lookup: dict[str, float] = {
        huc: sum(ratios) / len(ratios)
        for huc, ratios in huc12_ratio_sum.items()
    }'''

content = content.replace(old, new)

with open("validation_maps.py", "w") as f:
    f.write(content)

print("Done.")
